
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

package analizadorsintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INICIO_GRUPO = 14;
  public static final int MULTIPLICACION = 9;
  public static final int RAIZ = 13;
  public static final int IGUAL = 12;
  public static final int NEGATIVO = 8;
  public static final int LETRA = 3;
  public static final int DECIMAL = 16;
  public static final int DIVISION = 10;
  public static final int SUMA = 7;
  public static final int POTENCIA = 4;
  public static final int ERROR = 18;
  public static final int EOF = 0;
  public static final int INICIO_V = 5;
  public static final int FIN_V = 6;
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int FIN_GRUPO = 15;
  public static final int DELIMITADOR = 11;
  public static final int DPUNTOS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "LETRA",
  "POTENCIA",
  "INICIO_V",
  "FIN_V",
  "SUMA",
  "NEGATIVO",
  "MULTIPLICACION",
  "DIVISION",
  "DELIMITADOR",
  "IGUAL",
  "RAIZ",
  "INICIO_GRUPO",
  "FIN_GRUPO",
  "DECIMAL",
  "DPUNTOS",
  "ERROR"
  };
}

